PIA\appBundle\Entity\JobMessages:
    type: entity
    table: job_messages
    indexes:
        link_id:
            columns:
                - link_id
        job_node_id:
            columns:
                - job_node_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    manyToOne:
        link:
            targetEntity: Links
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                link_id:
                    referencedColumnName: Id
            orphanRemoval: false
        jobNode:
            targetEntity: JobNodes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                job_node_id:
                    referencedColumnName: Id
            orphanRemoval: false
    lifecycleCallbacks: {  }
