pia_login:
    path:     /login
    defaults: { _controller: PIABundle:Security:login }  
    
pia_logout:
    path:     /logout

pia_homepage:
    path:     /
    defaults: { _controller: PIABundle:Home:index }
    
pia_jobs:
    path:     /jobs       
    defaults: { _controller: PIABundle:Jobs:list }

pia_test_rules:
    path:     /test/{jobid}
    defaults: { _controller: PIABundle:TestRules:index }
    requirements:
        methods:  GET
        jobid: \d+
        
pia_get_groups:
    path:     /groups/{levelid}
    defaults: { _controller: PIABundle:TestRules:groups }
    requirements:
        methods:  GET
        levelid: \d+   
        
        
    
