pia_homepage:
    path:     /
    defaults: { _controller: PIABundle:Home:index }
    
pia_test_rules:
    path:     /test/{jobid}
    defaults: { _controller: PIABundle:TestRules:index }
    requirements:
        methods:  GET
        jobid: \d+
    
